name: Close stale issues and PRs
on:
  schedule:
    - cron: '45 * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9.0.0
        with:
          days-before-stale: 21
          days-before-close: 0
          operations-per-run: 300
          exempt-issue-labels: do-not-close
          exempt-pr-labels: do-not-close